# Data sources

Tobacco use had been more and more serious problem among youth these years. On Dec. 20, 2019, the federal minimum age for sale of tobacco product in the U.S. were raised from 18 to 21 years old. Still, youth in U.S. have some access to tobacco products. The main aim for our project is to find a pattern between youth and to provide a prevention on tobacco usage. 

The primary data sources we will use for this project is [National Youth Tobacco Survey](https://www.cdc.gov/tobacco/data_statistics/surveys/nyts/data/index.html) collected from CDC. 
NYTS has survey data from 1999-2020, due to the large sample size, we will only focus on data from 2016-2020 in this project.

## National Youth Tobacco Survey (NYTS)

Dataset used: `nyts-2020.xlsx`, `nyts-2019.xlsx`, `nyts-2018.xlsx`, `nyts-2017.xlsx`, `nyts-2016.xlsx`.

The National Youth Tobacco Survey provides us with survey data from young
people starting at the age of nine years old up through a 19 & older option. The
survey asks extensive questions related to tobacco including usage patterns,
recency, brand loyalty, and family/friend usage patterns. We intend to use
combinations of these answers to identify the patterns and trends of young
people. The survey is administered annually so we will be able to compare the
results of multiple years to see how trends have changed, if at all.

Issues we encountered:
- Although it would be nice to cross compare the trends over 20 years, survey questions and format of answers vary from year to year. Our solution is that we only selected \~30 important questions (columns) that appears in all 5 years related to our aim in this project. Also, dataset for one year have \~15000 rows and \~1000 columns, after preprocessing, we are dealing with (\~100000, 40), which is much smaller and precise dataset. 


```{r, eval=FALSE, echo=TRUE}
# Column names

# [1] "Year"                                                                                                                                                                                   
# [2] "How old are you?"                                                                                                                                                                       
# [3] "What is your sex?"                                                                                                                                                                      
# [4] "What grade are you in?"                                                                                                                                                                 
# [5] "No, not of Hispanic, Latino, Latina or Spanish origin: Are you Hispanic, Latino, Latina, or of Spanish origin? (Select one or more)"                                                    
# [6] "Yes, Mexican, Mexican American, Chicano, or Chicana: Are you Hispanic, Latino, Latina, or of Spanish origin? (Select one or more)"                                                      
# [7] "Yes, Puerto Rican: Are you Hispanic, Latino, Latina, or of Spanish origin? (Select one or more)"                                                                                        
# [8] "Yes, Cuban: Are you Hispanic, Latino, Latina, or of Spanish origin? (Select one or more)"                                                                                               
# [9] "Yes, Another Hispanic, Latino, Latina, or Spanish origin: Are you Hispanic, Latino, Latina, or of Spanish origin? (Select one or more)"                                                 
# [10] "American Indian or Alaska Native: What race or races do you consider yourself to be? (Select one or more)"                                                                              
# [11] "Asian: What race or races do you consider yourself to be? (Select one or more)"                                                                                                         
# [12] "Black or African American: What race or races do you consider yourself to be? (Select one or more)"                                                                                     
# [13] "Native Hawaiian or Other Pacific Islander: What race or races do you consider yourself to be? (Select one or more)"                                                                     
# [14] "White: What race or races do you consider yourself to be? (Select one or more)"                                                                                                         
# [15] "Have you ever smoked a cigarette, even one or two puffs?"                                                                                                                               
# [16] "How old were you when you first smoked a cigarette, even one or two puffs?"                                                                                                             
# [17] "About how many cigarettes have you smoked in your entire life?"                                                                                                                         
# [18] "During the past 30 days, on how many days did you smoke cigarettes?"                                                                                                                    
# [19] "When was the last time you smoked a cigeratte, even one or two puffs? (Please choose the first answer that fits)"                                                                       
# [20] "During the past 30 days, on the days you smoked, about how many cigarettes did you smoke per day? A pack usually has 20 cigarettes in it."                                              
# [21] "During the past 30 days, what brand of cigarettes did you usually smoke?"                                                                                                               
# [22] "Menthol cigarettes are cigarettes that taste like mint. During the past 30 days, were the cigarettes that you usually smoked menthol?"                                                  
# [23] "Have you ever been curious about smoking a cigarette?"                                                                                                                                  
# [24] "Do you think that you will try a cigarette soon?"                                                                                                                                       
# [25] "Do you think that you will smoke a cigarette in the next year?"                                                                                                                         
# [26] "If one of your best friends were to offer you a cigarette, would you smoke it?"                                                                                                         
# [27] "Have you ever smoked a cigar, cigarillo, or little cigar, even one or two puffs?"                                                                                                       
# [28] "How old were you when you first smoked a cigar, cigarillo, or little cigar, even one or two puffs?"                                                                                     
# [29] "Have you ever used chewing tobacco, snuff, or dip, even just a small amount?"                                                                                                           
# [30] "How old were you when you first used chewing tobacco, snuff, or dip, even just a small amount?"                                                                                         
# [31] "Have you ever been curious about using an e-cigarette?"                                                                                                                                 
# [32] "Have you ever used an e-cigarette, even once or twice?"                                                                                                                                 
# [33] "How old were you when you first used an e-cigarette, even once or twice?"                                                                                                               
# [34] "When you are using the Internet, how often do you see ads or promotions for cigarettes or other tobacco products?"                                                                      
# [35] "When you go to a convenience store, supermarket, or gas station, how often do you see ads or promotions for cigarettes or other tobacco products?"                                      
# [36] "When you watch TV or streaming services (such as Netflix, Hulu, or Amazon Prime), or go to the movies, how often do you see ads or promotions for cigarettes or other tobacco products?"
# [37] "When you are using the Internet, how often do you see ads or promotions for e-cigarettes?"                                                                                              
# [38] "When you go to a convenience store, supermarket, or gas station, how often do you see ads or promotions for e-cigarettes?"                                                              
# [39] "When you watch TV or streaming services (such as Netflix, Hulu, or Amazon Prime), or go to the movies, how often do you see ads or promotions for e-cigarettes?"                        
# [40] "How often do you see posts related to e-cigarettes when you go on social media (such as YouTube, Instagram, Snapchat, Twitter, or Facebook)?"                                                                                    

```