# Conclusion
After our exploration of the CDC's National Youth Tobacco Survery (NYTS) using the past five years, we discovered interesting trends surrounding tobacco interest and usage in the youth population of America. Through this exploration, we were able to address and answer a few questions surrounding youth tobacco behavior.

As we began our dive into the survey results, we were interested in how the younger population was being exposed to tobacco products. We investigated this further by looking at the questions related to advertisement placements. These questions asked the survey taker how often they saw ads on the Internet, in local stores, or on TV/streaming services. We observed that current trends show e-cigarette ads are increasing on the Internet and in stores more than they are on TV/steaming services. One reason for this may be that there are stricter rules on what is allowed to be advertised via TV/streaming that in stores and the Internet. It could also be a casualty of tobacco companies trying to advertise to adults who are in a store and could buy the products right away. A more macro influence that occurred in 2019 that could've led to the decrease in ads seen could be the legislation that increased the legal age to purchase tobacco products from 18 to 21 in 2019. This would've prompted tobacco companies to shift their target demographic for ads to a higher age.

Through our analysis, we also inspected the race and ethnicity of the youth population. Interestingly, we saw that nearly 1 in 4 of the youth that identify as Cuban and about 1 in 5 American Indian or Alaska Native youth have tried smoking before. As we looked for a reason for why this ratio may be so high, our best guess is that it may be related to cultural norms that are not present in other race and ethnicities. We were also surprised to see a range of almost a 13% difference between the lowest and highest percentage of youth who have tried smoking when broken down by race and ethnicity. This could suggest that tobacco companies may have unfair targeting strategies for youth in certain demographics more so than others. Further research behind specific tobacco companies may be needed to fully make this connection. 


